on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GITHUB_EVENT: '$GITHUB_EVENT'"
          echo "GITHUB_REF: '$GITHUB_REF'"
          echo "GITHUB_SHA: '$GITHUB_SHA'"
      - name: Diffset
        id: diffset
        uses: softprops/diffset@v1
        with:
          base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Diffset
        run: echo "${{ steps.diffset.outputs.files }}"